# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 17:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedToons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=12)),
                ('character_race', models.CharField(max_length=15)),
                ('character_faction', models.CharField(max_length=15)),
                ('character_server', models.CharField(max_length=20)),
                ('character_class', models.CharField(max_length=20)),
                ('character_spec', models.CharField(max_length=20)),
                ('character_level', models.IntegerField()),
                ('character_thumbnail', models.CharField(max_length=100)),
                ('character_equipped_ilevel', models.IntegerField()),
                ('character_legendaries', models.CharField(max_length=100)),
                ('character_progression', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Processed Characters',
                'db_table': 'processed_toons',
            },
        ),
        migrations.CreateModel(
            name='RequestedParses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_member', models.CharField(max_length=12)),
                ('requesting_member_realm', models.CharField(max_length=50)),
                ('group_string', models.TextField()),
                ('json_string', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Group Lookups',
                'db_table': 'group_lookup_requests',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50)),
                ('client_secret', models.CharField(max_length=50)),
                ('blizzard_api_url_base', models.CharField(max_length=100)),
                ('blizzard_api_image_url_base', models.CharField(max_length=100)),
                ('blizzard_armory_base_link', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Website Settings',
                'db_table': 'site_settings',
            },
        ),
    ]
