# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedtoons',
            name='group_lookup_trackback',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='frontdoor.RequestedParses'),
            preserve_default=False,
        ),
    ]
