# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0002_processedtoons_group_lookup_trackback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanHammer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontdoor.RequestedParses')),
            ],
            options={
                'db_table': 'banned_users',
                'managed': True,
                'verbose_name_plural': 'Banned Users',
            },
        ),
    ]
